### ISSUE TITLE
Feature: new Notification management?

### ISSUE THREAD

**Issue by dclausen01** [koyuawsmbrtn/bbz-cloud#21]
- [x] Event handling for emitted notification from remote sites
- [ ] opening the corresponding WebApp for each notification clicked on

**Comment by dclausen01** [comment]
https://www.jonic.cn/qa/?qa=1157594/javascript-intercept-html5-web-notifications-in-a-browser-environment

**Comment by koyuawsmbrtn** [comment]
:thinking:

**Comment by dclausen01** [comment]
seems not possible with actual framework. Until we change that, laying this dormant...

**Comment by dclausen01** [comment]
Ist durch "red dot" so gut gelöst, wie es geht!
