### ISSUE TITLE
Issue webapp can be disabled

### ISSUE THREAD

**Issue by koyuawsmbrtn** [koyuawsmbrtn/bbz-cloud#34]

**Comment by dclausen01** [comment]
???

**Comment by koyuawsmbrtn** [comment]
Man kann die Webapp deaktivieren, wo man Issues einreichen kann. Wenn man in den Einstellungen die Webapp wieder aktiviert führt das zu ein paar Bugs mit der Navigationsleiste.

**Comment by dclausen01** [comment]
Ok, das muss raus. Kannst Du das machen? Ich bastel nachher noch am Verhalten bei reload nach Standby (stay minimized und keep BrowserWindow-dimensions)

**Comment by koyuawsmbrtn** [comment]
Ich kann mich morgen mal ran setzen. War heute noch auf 'ner Demo und jetzt gleich Geburtstagsfeier.

**Comment by dclausen01** [comment]
Hab dir auf schul.cloud geantwortet ☺️
